module.exports = {
  login: "/login",
  configlogin:"/global-config/config-ui-login",
  config:"/global-config/config",
  configMap:"/global-config/config/configMap",
  staticKeys:"/global-config/config/staticKeys",
  supplierConfig:"/global-config/config/supplierConfig",
  configList:"/global-config/config/configList",
  citasLogin: "/staff/login",
  locations:"/location/fetchAll",
  updateLocation:"/location/update",
  addLocation:"/location/add",
  locationByStaffId:"/location/fetchServiceStaffDetails",
  deleteLocation:"/location/delete",
  addServie:"/services/add",
  getAllServices:"/services/fetchAll",
  deleteService:"/services/delete",
  fetchStaff:"/staff/fetchAll",
  addStaff:"/staff/add",
  deleteStaff: "/staff/delete",
  //config:"/global-config/config"
};
